#
###################################
# Site wide configuration
####################################
#
title: Apoorva Kumar
email:
description: The life of a bored robotocist
url: # the base hostname & protocol for your site
keywords: ["portfolio", "jekyll"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Apoorva Kumar
  avatar: me.jpg
  job: "A shit guy"
  bio: "I am a Robotics and Aritifical Intelligence pusruing my undegraduate degree in Electronics and Electrical Engineering at IIT Guwahati with minor in Computer Sciences and Engineering. \n Currently working as the secretary of Robotics Club my complete reserach intrest lies in the field of Robotics and applications of AI in the same. \n I am proficient in the use of robtics development frameworks like ROS and have quite good expreince working with sensors ranging from IMU's to RGBD Cameras. \n I am adept to code in Python(expreice in Keras, Tensorflow, and web-requests modeules), Java and C++."
  email:
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: #username
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
